### ISSUE TITLE
Not able to migrate app to nativescript 6 which supports only webPack work flow

### ISSUE THREAD

**Issue by kranthi-kiki** [nstudio/nativescript-loading-indicator#10]
With NativeScript 6.0 the Webpack workflow will be the only way of building apps. 
can you please provide when you are going to  add  Webpack feature.
We got stuck for this feature from migrating to Nativescript 6.0 . can you please update the plugin at the earliest.

![image](https://user-images.githubusercontent.com/46471488/64718767-7ad62f80-d4e4-11e9-84da-d4aa8ddc6ff5.png)

**Comment by bradmartin** [comment]
Please check the demos before opening these issues :). Thanks. They're working fine on NS6. I suggest you also open a suggestion to the NS team somehow to change their marketplace website as that is incorrect.
