### ISSUE TITLE
Loader doesn't show on Android and iOS

### ISSUE THREAD

**Issue by AgustinV08** [nstudio/nativescript-loading-indicator#12]
I created a new component in my Nativescript/Angular project and use the LoadingIndicator as normal like in my other components, but in the new component it doesn't show the LoadingIndicator

```
indicator = new LoadingIndicator();
showLoader()
    {
        const options: OptionsCommon = {
            message: "Cargando",
            dimBackground: true,
            color: '#FFFFFF',
            hideBezel: true,
            userInteractionEnabled: false,
            mode: Mode.Indeterminate,
            android: {
                cancelable: false,
            },
            ios: {
                square: false,
            }
        };

        this.indicator.show(options);
    }

    hideLoader()
    {
        this.indicator.hide();
    }
```

**Comment by bradmartin** [comment]
Have you checked the demo? It seems to work fine there. As well as in a couple apps I work on. Angular and plain NS, no issue.

**Comment by AgustinV08** [comment]
I checked the demo before and i follow the methods, what is weird for me, is how in my other components it works fine and in the new components is failing

**Comment by SerialAnonymous** [comment]
> 
> 
> I created a new component in my Nativescript/Angular project and use the LoadingIndicator as normal like in my other components, but in the new component it doesn't show the LoadingIndicator
> 
> ```
> indicator = new LoadingIndicator();
> showLoader()
>     {
>         const options: OptionsCommon = {
>             message: "Cargando",
>             dimBackground: true,
>             color: '#FFFFFF',
>             hideBezel: true,
>             userInteractionEnabled: false,
>             mode: Mode.Indeterminate,
>             android: {
>                 cancelable: false,
>             },
>             ios: {
>                 square: false,
>             }
>         };
> 
>         this.indicator.show(options);
>     }
> 
>     hideLoader()
>     {
>         this.indicator.hide();
>     }
> ```

have you succed?
