### ISSUE TITLE
Cannot find NAMESPACE android

### ISSUE THREAD

**Issue by gyansoft786** [nstudio/nativescript-loading-indicator#14]
ERROR in node_modules/@nstudio/nativescript-loading-indicator/index.d.ts(77,10): error TS2304: Cannot find name '**UIView**'.
node_modules/@nstudio/nativescript-loading-indicator/index.d.ts(85,10): error TS2503: Cannot find namespace '**android**'.

Successfully synced application org.nsf.mobileaudit on device HGAGQW7N.
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{org.nsf.mobileaudit/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nsf.mobileaudit/com.tns.NativeScriptActivity}: com.tns.NativeScriptExceptionSystem.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1083)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1063)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1055)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:19)
System.err:     at android.app.Activity.performCreate(Activity.java:6720)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
System.err:     ... 9 more

**Comment by bradmartin** [comment]
Your project shouldn't be scanning node_modules during build. Add `skipLibCheck: true` to your tsconfig.

**Comment by gyansoft786** [comment]
> Your project shouldn't be scanning node_modules during build. Add `skipLibCheck: true` to your tsconfig.

it didn't work. below is tsconfig

```

{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "skipLibCheck": true,
        "lib": [
            "es6",
            "dom",
            "es2015.iterable"
        ],
        "baseUrl": ".",
        "paths": {
            "~/*": [
                "src/*"
            ],
            "*": [
                "./node_modules/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "platforms"
    ]
}

```

**Comment by bradmartin** [comment]
Was it the same error? If so, then you might have a different config executing that is still looking in node_modules. You can extend `tsconfigs` in projects, which means overwrite different settings based on project setup.

**Comment by gyansoft786** [comment]
Problem solved.
i add `"skipLibCheck": true`, flag in tsconfig.json and tsconfig.tns.json files.

also delete node_modules, hooks, platforms folder and  package-lock.json file. Then run `npm i`
