### ISSUE TITLE
Having error of "_defaultProgressColor" of undefined

### ISSUE THREAD

**Issue by SerialAnonymous** [nstudio/nativescript-loading-indicator#15]
i am using nativescript+vuejs i have trieds like this and i am using with pure javascript. I tried the below code and i got "_defaultProgressColor" of undefined error

>  import {LoadingIndicator,Mode,OptionsCommon} from '@nstudio/nativescript-loading-indicator';
export default {
        data() {
            return {
                indicator: LoadingIndicator()
            }
        },
methods: {
        showLoader(){
            options: (OptionsCommon) = {
                message: 'Loading...',
                details: 'Additional detail note!',
                progress: 0.65,
                backgroundColor: 'red',
                android: {
                    cancelable: false,
                },
                ios: {
                    square: false,
                }
            };
            this.indicator.show(options);
        },
        hideLoader()
        {
            this.indicator.hide();
        }
}
``

**Comment by bradmartin** [comment]
I don't know Vue, but I don't see a `new` instance of the `LoadingIndicator` in your code. Unless in Vue the `return { indicator:...` executes the constructor (new instance) of the class then that's your issue.
