### ISSUE TITLE
Show method throwing error on Android

### ISSUE THREAD

**Issue by SmailHammour** [nstudio/nativescript-loading-indicator#17]
### Which platform(s) does your issue occur on?
- Android 
- Android version: 17 
- Emulator: Pixel 3

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.1.2
- Cross-platform modules: 6.0.1
- Runtime(s): 6.1.2
- Plugin(s): 
"dependencies": {
        "@angular/animations": "8.0.0",
        "@angular/common": "8.0.0",
        "@angular/compiler": "8.0.0",
        "@angular/core": "8.0.0",
        "@angular/forms": "8.0.0",
        "@angular/http": "8.0.0-beta.10",
        "@angular/platform-browser": "8.0.0",
        "@angular/platform-browser-dynamic": "8.0.0",
        "@angular/router": "8.0.0",
        "@ngx-translate/core": "^11.0.1",
        "@ngx-translate/http-loader": "^4.0.0",
        "@nstudio/nativescript-loading-indicator": "^2.0.0",
        "lodash": "^4.17.10",
        "nativescript-angular": "8.0.2",
        "nativescript-bitmap-factory": "^1.7.1",
        "nativescript-blur": "^2.0.0",
        "nativescript-email": "^1.5.3",
        "nativescript-geolocation": "5.1.0",
        "nativescript-google-maps-sdk": "^2.8.1",
        "nativescript-iqkeyboardmanager": "^1.3.0",
        "nativescript-phone": "^1.3.1",
        "nativescript-plugin-firebase": "^10.2.0",
        "nativescript-social-share": "^1.5.0",
        "nativescript-theme-core": "~1.0.4",
        "nativescript-toast": "^2.0.0",
        "nativescript-ui-listview": "^8.0.1",
        "nativescript-unit-test-runner": "0.7.0",
        "reflect-metadata": "~0.1.8",
        "rxjs": "6.3.3",
        "tns-core-modules": "6.0.1",
        "zone.js": "0.9.1"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "0.800.3",
        "@angular/compiler-cli": "8.0.0",
        "@types/jasmine": "^2.8.7",
        "@types/node": "^10.1.2",
        "babel-traverse": "6.26.0",
        "babel-types": "6.26.0",
        "babylon": "6.18.0",
        "codelyzer": "^5.2.0",
        "jasmine-core": "^3.1.0",
        "karma": "4.1.0",
        "karma-jasmine": "2.0.1",
        "karma-mocha-reporter": "^2.2.5",
        "karma-nativescript-launcher": "^0.4.0",
        "karma-webpack": "3.0.5",
        "lazy": "1.0.11",
        "nativescript-dev-webpack": "1.0.1",
        "prettier": "^1.19.1",
        "stylelint": "^12.0.0",
        "stylelint-config-standard": "^19.0.0",
        "stylelint-scss": "^3.13.0",
        "tns-platform-declarations": "^6.2.3",
        "tslint": "^5.20.1",
        "tslint-config-prettier": "^1.18.0",
        "typescript": "3.4.5"
    }

### Please, tell us how to recreate the issue in as much detail as possible. 
When i try to show the loader on Android i get the following error;
`TypeError: frame_1.Frame.topmost is not a function`

This happened after upgrading to NS6

**Comment by slomkae** [comment]
Dear @SmailHammour!

I have struggled the exact same issue today.
What solved it for me, was updating the following packages
**tns-core-modules -> ~6.23
nativescript-dev-webpack -> 1.3.0**

The other option is to revert to version 1 of the plugin
**@nstudio/nativescript-loading-indicator -> 1.0.0**

Hope this helps.

Elia

**Comment by SmailHammour** [comment]
Thanks @slomkae ! That worked!
