### ISSUE TITLE
[android] Calling js method onCreateView failed

### ISSUE THREAD

**Issue by kefahB** [nstudio/nativescript-loading-indicator#18]
Hi @bradmartin,

I have 2 projects one of them work fine and the other throw the error bellow ! I tried to resolve this error by many doing `rm -Rf node_modules hooks platforms`, do you have idea about this error ?

thanks

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method finishUpdate failed
System.err: TypeError: frame_1.Frame.topmost is not a function
System.err: 
System.err: StackTrace:
System.err: 	Frame: function:'push.../node_modules/@nstudio/nativescript-loading-indicator/loading-indicator.js.LoadingIndicator._createPopOver', file:'file:///node_modules/@nstudio/nativescript-loading-indicator/loading-indicator.js:217:0
System.err: 	Frame: function:'push.../node_modules/@nstudio/nativescript-loading-indicator/loading-indicator.js.LoadingIndicator.show', file:'file:///node_modules/@nstudio/nativescript-loading-indicator/loading-indicator.js:38:0
```

**Comment by bradmartin** [comment]
Not off top of my head, that seems really odd since the `topmost()` function should/is in nativescript's core-modules still. 

Are you doing anything differently with this project? Maybe calling the loading-indicator at a time in the app where something is possibly undefined 😕not really sure.

**Comment by kefahB** [comment]
Is really bizarre ! I I trying to debugging it ! I had upgrading `tns-core-modules` and it solved a part of problem .. I use tabview as a root and the first navigation between tabs work but the second one crash ! 

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: Error: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
System.err:     android.view.ViewRootImpl.setView(ViewRootImpl.java:798)
System.err:     android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
System.err:     android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
System.err:     android.widget.PopupWindow.invokePopup(PopupWindow.java:1434)
System.err:     android.widget.PopupWindow.showAtLocation(PopupWindow.java:1203)
System.err:     android.widget.PopupWindow.showAtLocation(PopupWindow.java:1170)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
`
``

**Comment by kefahB** [comment]
@bradmartin ,

I confirm that the error come from this module, I have debugged a lot today .. and when I disable all loader `show()` and `hide()` than Android dose not have a problem any more ! 

Only `show` method who dose the crash !

I work on the latest version of NS ans same for `tns-core-modules` and using the v2.0.0 for this module

**Comment by kefahB** [comment]
@bradmartin 
I got it finally  .. I think the problem come since that the `topmost` is deprecated with the latest version of tns-core-modules

- my first App run with `ths-core-modules` : `v6.0.1` and the `"@nstudio/nativescript-loading-indicator": "^1.0.0"` 
- the second one run with `ths-core-modules` : `v6.2.3` and the `"@nstudio/nativescript-loading-indicator": "^2.0.0"`

I do update the first one like the second one an I have received same crash .. the I do the inverse and my project dose work as expected 

Other observations : like I sed, I have tabView as a root and for each TabViewItem I have a Frame inside, the ONLY event that prevent the crash is `naigatingTo` .. I tried `loaded, nevigatedTo` and all of this do a crash ! To prevent the crash and keeping all event wok I tried the BottomNavigation and this prevent the crash !!

**Comment by kefahB** [comment]
Hi @bradmartin ,

Any work in progress for this issu ?

Thanks

**Comment by kefahB** [comment]
@NathanaelA please found [this sample](https://play.nativescript.org/?template=play-tsc&id=PpozvL&v=2) .. loading will work fist load .. if you change the tab and go back the app will crash !!

Crash info
```sh
[Galaxy S10]: An uncaught Exception occurred on "main" thread.
Calling js method onSelectedPositionChange failed
Error: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?

StackTrace:
LoadingIndicator._createPopOver(file:///data/data/org.nativescript.preview/files/app/@nstudio/nativescript-loading-indicator/loading-indicator.js:227:27)
at LoadingIndicator.show(file:///data/data/org.nativescript.preview/files/app/@nstudio/nativescript-loading-indicator/loading-indicator.js:38:22)
at HomeViewModel(file:///data/data/org.nativescript.preview/files/app/home/home-view-model.js:9:16)
```

Please I have disabled this plugin from all my apps because is crash it
