### ISSUE TITLE
Files missing after removing and adding plugin.

### ISSUE THREAD

**Issue by JanMarkD** [nstudio/nativescript-loading-indicator#23]
#19 # Which platform(s) does your issue occur on?
- Both 
- emulator or device. What type of device? Both

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it) 6.2.2
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project) 6.2.3
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project) 6.2.0 
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here) 2.0.0 and 2.0.2

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

Remove and add the plugin and the main ios.js, android.js and common.js files are missing.

### Is there any code involved? 
No

**Comment by jelledijkstra97** [comment]
I'm having this exact same problem. Specifying version 1.0.0 in the package.json solved it for me.

**Comment by keithgulbro** [comment]
I think 2.0.2 was shipped without proper testing. I'm encountering the following error:

```
Module not found: Error: Can't resolve '@nstudio/nativescript-loading-indicator' in ...
```

**Comment by bradmartin** [comment]
2.0.2 was a bad publish, `2.0.3` published moments ago should resolve the publishing issue.

**Comment by bradmartin** [comment]
`2.0.3` and `2.0.4` should be working fine to resolve this issue. Closing for now, please reopen if you encounter this again.
