### ISSUE TITLE
App crushes on show function

### ISSUE THREAD

**Issue by OPADA-Eng** [nstudio/nativescript-loading-indicator#24]
### Which platform(s) does your issue occur on?
-Android
-Android Api 29 
- emulator.

### Please, provide the following version numbers that your issue occurs with:
- CLI: 6.3.2
- Cross-platform modules: ^6.3.2
- Runtime(s): `"tns-android" : "6.3.1"` 

### Please, tell us how to recreate the issue in as much detail as possible. 
install the plugin and run show function.

### Is there any code involved? 

> System.err: An uncaught Exception occurred on "main" thread.
> System.err: Calling js method run failed
> System.err: TypeError: Cannot read property 'push' of undefined
> System.err: 
> System.err: StackTrace:
> System.err: (file:///node_modules/@nstudio/nativescript-loading-indicator/loading-indicator.js:41:0)
> System.err:     at invoke(file:///node_modules/@nativescript/core/timer/timer.js:20:30)
> System.err:     at run(file:///node_modules/@nativescript/core/timer/timer.js:24:0)
> System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
> System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
> System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
> System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1160)
> System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1138)
> System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1134)
> System.err:     at com.tns.gen.java.lang.Runnable.run(Runnable.java:17)
> System.err:     at android.os.Handler.handleCallback(Handler.java:883)
> System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
> System.err:     at android.os.Looper.loop(Looper.java:214)
> System.err:     at android.app.ActivityThread.main(ActivityThread.java:7356)
> System.err:     at java.lang.reflect.Method.invoke(Native Method)
> System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

it seems that the npm version does not have the latest code here in git repository.
please check the versions.

**Comment by wendt88** [comment]
same here

**Comment by bradmartin** [comment]
`2.0.4` published to init the array which should resolve this.
