### ISSUE TITLE
Message and Details are not displayed on iOS

### ISSUE THREAD

**Issue by mhtghn** [nstudio/nativescript-loading-indicator#27]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS
- iOS Version : 13.1
- What type of device? Emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.3.3
- Cross-platform modules: 6.3.2
- Runtime: 6.3.0 
- Plugin: 2.0.4

### Please, tell us how to recreate the issue in as much detail as possible. 
When displaying the loading indicator with message and details, only the spinner is shown. There are no message and details. This only occurs on iOS, on Android it is displayed. See code below

### Is there any code involved? 
```typescript
import {
    LoadingIndicator,
    Mode,
    OptionsCommon
} from "@nstudio/nativescript-loading-indicator";

...

const indicator = new LoadingIndicator();

const options: OptionsCommon = {
            message: "Chargement...",
            details: "Récupération de la liste des notifications",
            margin: 10,
            dimBackground: true,
            color: "#85247b", // color of indicator and labels
            // background box around indicator
            // hideBezel will override this if true,
            userInteractionEnabled: false, // default true. Set false so that the touches will fall through it.
            mode: Mode.Indeterminate // see options below
};
indicator.show(options);
```

**Comment by AgustinV08** [comment]
Same issue here

**Comment by bbc91** [comment]
I'm having the same issue. After I updated my nativescript-core-modules from 6.0.1 to 6.3.2, the problem appeared. I don't have a solution for now except doing back to previous version.

**Comment by bradmartin** [comment]
Have confirmed this is an issue, thanks for reporting.

**Comment by bradmartin** [comment]
So looks like the native iOS pod released a version and since this plugin wasn't pinning a version it pulled the latest pod which appears to have changed how you set the text of the label and other properties :) so I'm looking to see all the breaking changes and just updating with the latest instead of pinning to the previous to future proof for now.

https://github.com/nstudio/nativescript-loading-indicator/blob/master/src/platforms/ios/Podfile#L1 not pinning here is why

**Comment by bradmartin** [comment]
`3.0.1` published with fixes.

**Comment by JamesPJ** [comment]
> `3.0.1` published with fixes.

Where is this release. I can't find it on the list...
