### ISSUE TITLE
Mode: Indeterminate won't close in Android and iOS

### ISSUE THREAD

**Issue by DepickereSven** [nstudio/nativescript-loading-indicator#28]
### Which platform(s) does your issue occur on?
- Android device (v8.1.0)
- iOS Emulator it also doesn't work

### Please, provide the following version numbers that your issue occurs with:

```
"nativescript": "6.3.2"
"nativescript-vue": "^2.5.0-alpha.3",
"@nstudio/nativescript-loading-indicator": "^2.0.4",
"tns-core-modules": "~6.3.2",
```

### Please, tell us how to recreate the issue in as much detail as possible. 

I want to use a loading indicator when I check a few variables before I send an HTTP request.
When the request is returned I close the loading indicator and go to another page.
But besides that. I want to close the loading indicator also in other cases.

- Like when some variable isn't filled in.
- When you have no internet connection
- When there isn't a possible HTTP response (what you ask don't exist).

So when everything is alright (everything is correctly filled in).
And there is a possible response then he will close the loading indicator. 
Otherwise, in other cases, It will keep the loading indicator.

### Is there any code involved? 

```js
const moment = require('moment');
import {
    LoadingIndicator,
    Mode
} from '@nstudio/nativescript-loading-indicator';

export default (function () {

    let indicator = new LoadingIndicator();

    const checkIfTheValuesAreCorrectBeforeWeCanStartSearchingAfterPossibleRoute = async function (_self, requestBuilderForSelect) {
        startLoadingModal();
        if (_self.data.routeDetails.time.date.real === null) {
            assignTimeToRouteDetailsWhenEmpty(_self);
        }
        if (isEmpty(_self.data.routeDetails.departure.details) || isEmpty(_self.data.routeDetails.arrival.details)) {
            startOrAndEndpositionIsntFilledIn(_self);
        } else {
            await getPossibleRoutes(_self, requestBuilderForSelect);
        }
    };

    function assignTimeToRouteDetailsWhenEmpty(_self) {
        _self.data.routeDetails.time.date.show = _self.formatTimeStampBasedOnLanguage.formatTimeStampForShowingSelect(_self);
        _self.data.routeDetails.time.date.real = moment().locale('en').format('YYYYMMDD');
        _self.data.routeDetails.time.time = _self.data.routeDetails.time.hint.replace(_self.data.routeDetails.time.date.show, '');
    }

    async function getPossibleRoutes(_self, requestBuilderForSelect) {
        await checkIfRouteCanBeFound(_self, requestBuilderForSelect);
    }

    /***************** HANDLE - ROUTES - ERROR *****************/

    async function checkIfRouteCanBeFound(_self, requestBuilderForSelect) {
        let isError = await requestBuilderForSelect.checkIfThereIsAPossibleRoute(_self);
        switch (isError) {
            case null:
                showNoInternetConnection(_self);
                break;
            case true:
                showErrorMessageWhyRouteCantBeFound(_self);
                break;
            case false:
                await goToTheResultPage(_self);
                break;
        }
    }

    async function goToTheResultPage(_self) {
        await _self.$goto('Route', {
            props: {
                routeDetails: _self.data.routeDetails,
                timeTable: _self.timeTable,
                indexWithClosestToRealTime: _self.indexWithClosestToRealTime
            }
        });
        stopLoadingModal();
    }

    /***************** ERROR - MESSAGES *****************/

    function startOrAndEndpositionIsntFilledIn(_self) {
        stopLoadingModal();
        showError(_self, _self.data.error);
    }

    function showErrorMessageWhyRouteCantBeFound(_self) {
        stopLoadingModal();
        showError(_self, _self.timeTable.msg);
    }

    function showNoInternetConnection(_self) {
        stopLoadingModal();
        internetError(_self);
    }

    /***************** HELP - FUNCTIONS *****************/

    function isEmpty(obj) {
        return !obj.hasOwnProperty('routeCode')
    }

    function startLoadingModal() {
        indicator.show({
            dimBackground: true,
            hideBezel: true,
            userInteractionEnabled: false,
            mode: Mode.Indeterminate
        });
    }

    function stopLoadingModal() {
        indicator.hide();
    }

    function showError(_self, errorMessage) {
        _self.feedback.error({
            title: "Error",
            message: errorMessage,
            duration: 6000
        })
    }

    function internetError(_self) {
        _self.feedback.warning({
            title: "No Internet Connection",
            message: _self._self.data.internetError,
            duration: 6000
        })
    }

    return {
        checkIfTheValuesAreCorrectBeforeWeCanStartSearchingAfterPossibleRoute,
    }

})();


```

## Explanation of the code

1.  The start is at `checkIfTheValuesAreCorrectBeforeWeCanStartSearchingAfterPossibleRoute()`. He will start the loadingModal with the function `startLoadingModal()`. 
2. If something isn't correctly filled in he will execute the function `startOrAndEndpositionIsntFilledIn` and then it should stop the loading indicator. But that doesn't happen.
3. If everything is correctly filled in he will do the following function `checkIfRouteCanBeFound`.
4. In that function, he will send the request with the data you provide.
5. The response will have 3 different states
5.1. `null` means no internet connection. Then he will execute `showNoInternetConnection` and close the loading indicator. But that doesn't happen.
5.2 `true` means data can't be found. Then he will execute `showErrorMessageWhyRouteCantBeFound`  and close the loading indicator. But that doesn't happen.
5.3. `false` means request when successful. Then he will execute `goToTheResultPage` and navigate to another page and close the loading indicator. That is the only function that will close the loading indicator.

**Comment by bradmartin** [comment]
Can you try with version `2.0.5` - it changed the way the `hide` method was iterating the instances and the demo app is working fine now. If you're still having trouble let us know. I'm unable to get any instance to not `hide` by calling `hide` on the `LoadingIndicator` instance that was shown.

**Comment by bradmartin** [comment]
I just tested this in the iOS Simulator with the latest version of the demo app and everything seems to be working as it should. If you're having trouble closing the indicator with your app, it's possible you have some logic changes needed or you're losing the instance of the indicator. I didn't read through that snippet in detail to confirm but that's the best guess I have ATM since it appears to be working fine under the demo app.

**Comment by DepickereSven** [comment]
Thank you very much for the fast response! 
I tried version `2.0.5` it works. I also tried your last update `3.0.1` it works there in to.
Thank you very much 👍.
