### ISSUE TITLE
Still doesn't work in Angular

### ISSUE THREAD

**Issue by dottodot** [nstudio/nativescript-loading-indicator#3]
I've tried this version since it was suggested that it now works in Angular

https://github.com/NathanWalker/nativescript-loading-indicator/issues/65#issuecomment-510573809

but it still doesn't display. I don't get any errors just can't get it to show.

```
export class LoadingService {
  options: any = {
    ios: {
      backgroundColor: 'yellow',
      color: '#000000'
    }
  };
  constructor(private loader: LoadingIndicator) {}

  show() {
    this.loader.show(this.options);
  }

  hide() {
    this.loader.hide();
  }
}

```

**Comment by bradmartin** [comment]
Where are you creating an instance of the loader? This isn't done internally, so you need to create an instance. The readme docs should help 👍

With that said, a good enhancement to the plugin might be to add an angular module that does create the instance that can be injected into your services/components. Would you be interested in making a PR for that?

**Comment by dottodot** [comment]
OK so I've tried the following and still not seeing the indicator.

```
  show() {
    const indicator = new LoadingIndicator();
    indicator.show(this.options);
  }
```

**Comment by Bidou44** [comment]
I have the same issue, not working with angular, @bradmartin can you please confirm? Or were you successful with angular?

Edit: Well, doing additional tests showed that it's working on some pages and not on other... have to find out what triggers the problem.

Second edit: @dottodot Ok, usually it's working if you do everything in the constructor. But I have at least one view were it's not working, I had to add a loaded event and put the show method there...

**Comment by bradmartin** [comment]
Yes I have this working in a current up to date NG app here: https://github.com/Max-Mobility/permobil-client/tree/master/apps/mobile/pushtracker

So something odd is happening with the projects I guess, maybe timing related like you mentioned @Bidou44 with the `loaded` event

**Comment by felixelgato92** [comment]
@dottodot I believe the backgroundColor and color options are part of common options now, so they should be outside of ios. I'm not sure if that's your issue. Give it a try

So your options const should look like this:

```
options: any = {
    backgroundColor: 'yellow',
    color: '#000000'
  };
```

**Comment by bradmartin** [comment]
The demo seems to be working properly. If more info with some code can show how to encounter the issue it'll help to find a fix.
