### ISSUE TITLE
Android is error, using Nativescript 6.0.0

### ISSUE THREAD

**Issue by ukik** [nstudio/nativescript-loading-indicator#30]
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method run failed
System.err: TypeError: frame_1.Frame.topmost is not a function
System.err:
System.err: StackTrace:
System.err:     Frame: function:'LoadingIndicator._createPopOver', file:'file:///node_modules\@nstudio\nativescript-loading-indicator\loading-indicator.js:236:33
System.err:     Frame: function:'', file:'file:///node_modules\@nstudio\nativescript-loading-indicator\loading-indicator.js:41:26
System.err:     Frame: function:'invoke', file:'file:///node_modules\tns-core-modules\timer\timer.js:19:47
System.err:     Frame: function:'run', file:'file:///node_modules\tns-core-modules\timer\timer.js:23:12
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err:     at com.tns.gen.java.lang.Runnable.run(Runnable.java:17)
System.err:     at android.os.Handler.handleCallback(Handler.java:873)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:226)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7209)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

**Comment by alonstar** [comment]
I have the same issue using Nativescript 6.1.0 and angular 8.2 and @nstudio/nativescript-loading-indicator v2.0.5

**Comment by Codex-** [comment]
I've been noticing this too, will try take a look

**Comment by Codex-** [comment]
Have had a look and so far have found it difficult to reproduce this with Nativescript 6.3.3.

Can you provide more information about the options you're using to trigger this? Or a sample app?

**Comment by aryanarcilia** [comment]
I get same error. Version 3.0.1 on NPM do not match with code in git master branch.
In version 3.0.1  use ```frame_1.Frame.topmost``` But on master branch also use ```frame_1.topmost```.

With tns core module 6.1.0 ``frame_1.Frame.topmost```  is not exist function. I think this issue only on tns core module < 6.3. You can not reproduce with 6.3.
nativescript-loading-indicator 2.0.5 and 3.0.1 is same error.

```tns --version : 6.1.0```
 
Here is my package.json
```
{
  "nativescript": {
    "id": "com.example.project",
    "tns-android": {
      "version": "6.1.2"
    },
    "tns-ios": {
      "version": "6.1.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "scripts": {
  },
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@ngrx/effects": "^8.6.0",
    "@ngrx/store": "^8.6.0",
    "@ngx-translate/core": "10.0.2",
    "@ngx-translate/http-loader": "3.0.1",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "moment": "^2.24.0",
    "nativescript-angular": "~8.2.0",
    "nativescript-audio-player": "^1.0.3",
    "nativescript-background-http": "^4.2.1",
    "nativescript-cfalert-dialog": "^1.0.15",
    "nativescript-exoplayer": "^4.0.1",
    "nativescript-image-cache-it": "^5.0.0-beta.6",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-mediafilepicker": "^2.0.18",
    "nativescript-ngx-fonticon": "^5.0.2",
    "nativescript-rotate-3d": "^0.8.0",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-toast": "^2.0.0",
    "nativescript-ui-listview": "8.0.1",
    "nativescript-ui-sidedrawer": "8.0.0",
    "nativescript-urlhandler": "^1.3.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "6.2.1",
    "rxjs-compat": "6.2.1",
    "tns-core-modules": "~6.1.0",
    "tns-platform-declarations": "^6.3.2",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "8.2.0",
    "@ngtools/webpack": "8.2.0",
    "codelyzer": "~4.5.0",
    "nativescript-dev-webpack": "^1.2.1",
    "node-sass": "^4.7.1",
    "tslint": "~5.19.0",
    "typescript": "~3.5.3"
  },
  "readme": "NativeScript Application"
}

```

**Comment by Codex-** [comment]
I believe that there will be a release soon with a PR that I have open at the moment #32 

After this release, this should be fixed too

**Comment by bradmartin** [comment]
`3.0.2` will be published shortly. Trying to find my publish codes for npm at the moment 😄

**Comment by Codex-** [comment]
@ukik @lecaobaophuc0912 can you please update and advise if the error still occurs for you?

**Comment by aryanarcilia** [comment]
Ok. I have upgrade project and it was resolved. Thank you
