### ISSUE TITLE
Error building iOS:  CDN: trunk URL couldn't be downloaded...

### ISSUE THREAD

**Issue by dpdragnev** [nstudio/nativescript-loading-indicator#34]
Hello,

When I try to build my 6.3.0 NS Core app on my Mac (local build, using tns build ios), I get the following error:

**CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/c/8/7/MBProgressHUD/1.2.0/MBProgressHUD.podspec.json Response: 302**

I think the problem is with the SSL certificate of the githubusercontent.com, because I tried getting the JSON file in the browser and I got a certificate error.

Has anyone else seen that?  What is the solution to move past this issue?

Thanks.

**Comment by bradmartin** [comment]
Never seen that. Maybe do `pod repo update` locally on your mac, there are some other pod commands but maybe that one will fix what you have going on.

**Comment by dpdragnev** [comment]
Thanks @bradmartin I tried that, but no luck.

**Comment by bradmartin** [comment]
Interesting, this might be something you have better luck searching for cocoapod related issues on StackOverflow. Don't think there's much we can do on our side with the plugin anyway :)

**Comment by dpdragnev** [comment]
Thanks @bradmartin I will do that and will post the solution if I find one.

**Comment by dpdragnev** [comment]
Ok,  so it was a network problem.  I disconnected from our company network and used my personal hotspot and voila, everything worked.  

I am not sure what the issue is, our network admin is looking into it.  If I get any more relevant information, I will post it here.
