### ISSUE TITLE
Error: Can't find `UIView` and `android`

### ISSUE THREAD

**Issue by jannomeister** [nstudio/nativescript-loading-indicator#4]
see attached screenshot
<img width="749" alt="Screen Shot 2019-07-25 at 3 24 42 PM" src="https://user-images.githubusercontent.com/46916819/61854342-76cc5f00-aef0-11e9-9b60-a38e40f41eb8.png">

**Comment by jannomeister** [comment]
I fixed it by adding `tns-platform-declarations`. But is there any future updates that the plugin will handle this one?

**Comment by bradmartin** [comment]
https://github.com/nstudio/nativescript-loading-indicator/issues/1#issuecomment-511028821
