### ISSUE TITLE
Long messages do not line break in iOS

### ISSUE THREAD

**Issue by jasonfrasch** [nstudio/nativescript-loading-indicator#42]
Long messages do not line break in iOS, the message is cut off on the first/only line.

### Which platform(s) does your issue occur on?
- iOS
- emulator and device

### Please, provide the following version numbers that your issue occurs with:
^3.0.3

Describe the steps to reproduce it.
Use a long "message".

This fixes it in my project:
https://github.com/nstudio/nativescript-loading-indicator/compare/master...jasonfrasch:patch-1 

I can submit a PR from my branch if you like.

**Comment by bradmartin** [comment]
PR def. appreciated for this 💯
