### ISSUE TITLE
Cannot find name 'UIView' 

### ISSUE THREAD

**Issue by kranthi-kiki** [nstudio/nativescript-loading-indicator#7]
> :app:mergeDebugAssets > Resolve files of :app:debugRuntimeClasspath
2304: Cannot find name 'UIView'.
> :app:mergeDebugAssets
<========-----> 65% EXECUTING [54s]
**node_modules/@nstudio/nativescript-loading-indicator/index.d.ts(77,10): error TS2304: Cannot find name 'UIView'.**
> :app:mergeDebugAssetsativescript-loading-indicator/index.d.ts(85,10): error TS

**Comment by bradmartin** [comment]
Closing in favor of #1
