### ISSUE TITLE
@nstudio/@nstudio/nativescript-loading-indicator name can only contain URL-friendly characters 

### ISSUE THREAD

**Issue by kefahB** [nstudio/nativescript-loading-indicator#9]
Hi,

I get this error when I do : 
> tns run android

```js
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "@nstudio/@nstudio/nativescript-loading-indicator": name can only contain URL-friendly characters
```

Thanks

**Comment by kefahB** [comment]
Hi @bradmartin,

Do you have already this issue ?

Thanks

**Comment by bradmartin** [comment]
Only guess is that you have something incorrect in your package.json.

The `@nstudio` scope shouldn't be there twice, as for the URL friendly characters. Never seen that problem before. Using the `@` symbol is common in npm packages. Example is `@angular`, all their packages are scoped under the `@angular` tag so it's "valid" as far as I know.

**Comment by kefahB** [comment]
Hi, I founded the issue ! When I switch from your old plugin to ´nstudio’  .. my app is already lunched .. when I do replace all import from ´nativescript-loading-indicator’ to ‘@nstudio/‘ on vscode the package.json and pachage-lock.json are edited by the cli and become ‘@nstudio/@nstudio/...’ !!!!
